#script to calculate the pnorm pval using the pval of gwas.
# pval.gwas is calculated using the saved -log10(pval) in the *obsRandomVals.rda files
#rm(list=ls())
#get the rda files ot be processed
BASEDIR <- "/home/kdsa/bootstrap/"
library(data.table)
source( paste0(BASEDIR, "scripts/randInteRandomisation_Zscorefunctions.R"))


#functions
#----------

#function to get the files to process for enrichment using the gwas pval
#5-30% - 5% increments
#40-100% in 10% incremetns

getFnames <- function(rdadir, totASE=8892) {
  # for % of ASEs
  #totASE <- 8892
  #lstpct <- c(30, 25, 20, 15 )
  lstpct <- c(seq(5,30, by=5), seq(40,100, by = 10 ))
  
  lstnASEs <- lapply(lstpct, function(pct){
    nASEs <- round ((pct/100)*totASE )
    return(data.table(pct, nASEs))
  })
  dtnASEs <- rbindlist(lstnASEs)
  lstnASEs <- dtnASEs$nASEs
  toMatch <- paste0(lstnASEs, collapse = "|")
  flist <- list.files(rdadir, pattern="*obsRandomVals.rda", recursive = T, full.names = T)
  head(flist,2)
  flist <- flist[ grep(toMatch, flist) ]
  
  flist <- flist[ grep("_neglog", flist) ]
  #check
  #recs <- strsplit(flist, "/") ; head(recs, 2) ;unique( sapply( recs, function(z) z[8] )); rm(recs)
  return(flist)
}

#calculates the zscores and pnorm pval(lower and upper tail false, )
calculateZscoresPnorm4GwasPval <- function( rda) {
  #prev_field4mean <- "neglogpval"
  #new_field4mean <- "p"
  
  #rda <- flist[1]
  load(rda)
  #ls()
  nOverlapSNPs <- nrow(q1data.overlap)
  #calculate the p from the neglogpval i.e. -log10(p)
  ran.from.q2data.overlap$p <- 10^(-ran.from.q2data.overlap$neglogpval)
  q1data.overlap$p <- 10^(-q1data.overlap$neglogpval)
  
  #head(q1data.overlap, 2)
  #head(ran.from.q2data.overlap, 2)
  setDT(ran.from.q2data.overlap)
  
  #calculate mean of the pvals
  ranmean_val<- ( ran.from.q2data.overlap[ , .(mean_pval=mean(p)), by=.(perm.no)])
  obsmean_val <- mean( q1data.overlap$p )
  #head(ranmean_val)
  rm(q1data.overlap, ran.from.q2data.overlap)
  # calculate the zscores and pnorm pvals with the both lower tail true and false 
  fname.prefix <- paste0("gwasPval_", gsub("_obsRandomVals.rda", "", basename(rda)))
  fname.prefix <- paste0(dirname(rda), "/",fname.prefix)
  #setwd("~/bootstrap/results/");fname.prefix <- paste0("gwasPval_", gsub("_obsRandomVals.rda", "", basename(rda)))
  
  return( calculatePvals_upperLowerTail (obsmean_val, ranmean_val$mean_pval, nOverlapSNPs, fname.prefix ) )
  
}

calculatePvals_upperLowerTail <- function(obs.meanval, ran.meanvals, nOverlaps, fname.prefix ) {
  #nOverlaps = no. of category SNPs that overlap with the source i.e. reference e.g. ASE GWAS overlap
  #fname.prefix = used for the plot title and plot saved as <fname.prefix>_DistributionPvalZscore.pdf
  #               and rda file for the zscores and pval calculated
  
  #calls the functios to calculate the zscores and pnorm
  # return the pval ( generated by pnorm)
  #Also saves the plot the distribution of the observed and ran zscores
  #obs.meanval<- obsmean_val; ran.meanvals <- ranmean_val$mean_pval;  nOverlaps <- nOverlapSNPs
  
  zscores <- calculateRanObsZscoresPnorm( obs.meanval, ran.meanvals, nOverlaps )
  obs.zscores <-  unlist(zscores[OBSZ] )
  ran.zscores <- unlist ( zscores[RANZ] )
  pnorm.pval <- unlist ( zscores[PNORM] )
  #calculate the pval with lower.tail=T
  pnorm.val.lowerTail.T <- pnorm( obs.zscores,lower.tail=T)
  
  fname <- paste0(fname.prefix, "_DistributionPvalZscore.pdf" )
  title <- paste0(fname.prefix, ":Distribution of Zscores-Random \n Observed Zscore =", obs.zscores )
  plotDistributionVals( obs.zscores, ran.zscores, fname, title )
  cat("\n Zscore distribution plot : ", fname, "\n")
  
  #save the zscores and pnorm
  fname <- paste0(fname.prefix, "_obsRandomValsZscorePval.rda" )
  
  save( obs.zscores, ran.zscores, pnorm.pval, pnorm.val.lowerTail.T, file=fname, compress=TRUE)
  cat("\n Zscores, p-value saved in : ", fname, "\n")
  
  return ( list(pnorm.pval, pnorm.val.lowerTail.T ))
  
}


#End functions
#-------------

rdadir <- paste0(BASEDIR, "results/varyingAseNum/")
nASE <- 15144
filelst <- getFnames(rdadir, nASE)
#filelst <- "/home/kdsa/bootstrap/results/varyingAseNum//aseNum8892_neglog/varASENum_SCZ2018_totSim1nIter10000_nCs8892_sim1_obsRandomVals.rda"
#system.time(pvals <- calculateZscoresPnorm4GwasPval( filelst) ) #58secs

lapply(filelst, function(f){
  pvals <- calculateZscoresPnorm4GwasPval( f) 
  cat( "\n", basename(f), ":", unlist(pvals))
  
})
date()
cat("\n End")
