#functions to calculate the pvalue using zscores


OBSZ <- 1  #obs zscore
RANZ <- 2 #ran zscore
PNORM <- 3

calculateRanObsZscoresPnorm <- function( obs.val, ran.vals, nOverlaps=NA ) {
  #obs.val = observed mean value
  #ran.vals= list of random means
  # nOverlaps= no. of Cs SNPs that overlapped with the ref/Source [ no. of randomly selected SNPs in each iteration of the bootstrap]
  #Not needed as the formula has chnaged
  # function returns a list of the observed,random zscores, pnorm value
  
  mean.ranvals <- mean( ran.vals)
  
  sd.ranvals <- sd( ran.vals)
  
  #Calculate the z-score for each permutation:
  #Z-score = (( e(G)-  e(X)))/(sd/sqrt(n)  )  (n= no. of overlaps)
  nPm <- 1: length(ran.vals)
  # cat(nPm, "\n")
  
  #nPm <- head(nPm)
  ran.zscores <-  lapply( nPm, function( y, all.ran ) {
    p <- all.ran[y]
    #Calculate the z-score
    #z <- ( p - mean.ranvals)/ (sd.ranvals/sqrt(nOverlaps) )
    z <- ( p - mean.ranvals)/ (sd.ranvals)
    return( z)
  }, all.ran <- ran.vals  )
  
  ran.zscores <- unlist (ran.zscores)
  #cat( "\n length", length( ran.zscores))
  #Calculate the z-score for the observed overlap
  #obs.zscore <- ( obs.val - mean.ranvals)/ ( sd.ranvals/sqrt(nOverlaps) )
  obs.zscore <- ( obs.val - mean.ranvals)/ ( sd.ranvals )
  
  #calculating the pnorm
  pnorm.val <- pnorm( obs.zscore,lower.tail=F)
  
  return ( list(obs.zscore, ran.zscores, pnorm.val ))
}




plotDistributionVals <- function( obs.val, ran.vals, fname, plot.title ) {
  #function to plot the distribution of the observed and random values provided
  # fname = pdf file name to save the plot
  #plot.title = title to be assigned to the plot
  
  min.val <- min( ran.vals,  obs.val )
  max.val <- max( ran.vals,  obs.val )
  x.ax.lim <- c(  min.val - 0.1, max.val +0.1  )
  title.size <- 0.75
  
  pdf(file=fname)
  
  #hist(ran.vals, xlab= "ran.vals", main= plot.title )
  hist(ran.vals, xlim=x.ax.lim , xlab= "ran.vals", main= plot.title, cex.main=title.size  )
  abline( v= obs.val, col="red", lty=2 )
  text( obs.val  , -5, "obs.val", 1, col="red", cex=0.6)
  
  dev.off()
  
  return(T)
}

getPval <- function(obs.meanval, ran.meanvals, nOverlaps, fname.prefix ) {
  #nOverlaps = no. of category SNPs that overlap with the source i.e. reference e.g. ASE GWAS overlap
  #fname.prefix = used for the plot title and plot saved as <fname.prefix>_DistributionPvalZscore.pdf
  #               and rda file for the zscores and pval calculated
  
  #calls the functios to calculate the zscores and pnorm
  # return the pval ( generated by pnorm)
  #Also saves the plot the distribution of the observed and ran zscores
  
  zscores <- calculateRanObsZscoresPnorm( obs.meanval, ran.meanvals, nOverlaps )
  obs.zscores <-  unlist(zscores[OBSZ] )
  ran.zscores <- unlist ( zscores[RANZ] )
  pnorm.pval <- unlist ( zscores[PNORM] )
  
  fname <- paste0(fname.prefix, "_DistributionPvalZscore.pdf" )
  title <- paste0(fname.prefix, ":Distribution of Zscores-Random \n Observed Zscore =", obs.zscores )
  plotDistributionVals( obs.zscores, ran.zscores, fname, title )
  cat("\n Zscore distribution plot : ", fname, "\n")
  
  #save the zscores and pnorm
  fname <- paste0(fname.prefix, "_obsRandomValsZscorePval.rda" )
  
  save( obs.zscores, ran.zscores, pnorm.pval, file=fname, compress=TRUE)
  cat("\n Zscores, p-value saved in : ", fname, "\n")
  
  return ( pnorm.pval )
  
}

getPvalUsingZscore <- function( obsRandomValsrda, outdir)
{
  #calls the function to calculate the zscore and the pnorm using the observed and random bootstrap values in the rda file.
  # saves the zscore, pnorm calculated.
  
  #returns the pnorm pval
  
  #obsRandomValsrda <- rdafile
  load(obsRandomValsrda)
  fname.prefix <- gsub("_obsRandomVals.rda", "", basename(obsRandomValsrda) )
  currdir <- getwd()
  cat("\n rdafile= ", obsRandomValsrda, "\n")
  cat("Outfut folder= ", outdir , "\n")
  cat("Output file prefix= ", fname.prefix, "\n")
  setwd(outdir)
  pval <- getPval(obs.meanval, ran.meanvals, nrow(q1data.overlap), fname.prefix )
  setwd(currdir)
  return( pval)
}

